name: Windows RDP Ngrok

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .
        mkdir ngrok

    - name: Set Ngrok Authtoken
      run: .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH }}

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user Administrator "RdpPass123!"

    - name: Start Ngrok Tunnel
      run: .\ngrok.exe tcp 3389 --region ap > tunnel.txt &
      shell: powershell

    - name: Display RDP Info
      run: |
        echo "Tunggu 25-40 detik..."
        Start-Sleep -Seconds 35
        type tunnel.txt
